core/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='admin/')),  # Adicione esta linha
]

apps/user/models.py
from datetime import date, timezone

from django.core.exceptions import ValidationError
from validate_docbr import CPF
from django.core.validators import MinLengthValidator
from django.db.models import Sum
from django.shortcuts import render
from decimal import Decimal
from django.utils import timezone



from django.db import models

def validate_uf(value):
    if not value.isalpha() or not value.isupper():
        raise ValidationError(
            'A UF deve conter apenas letras, sendo elas Maiúsculas')

#Criação do atributos de Lote, Categoria e User
class Lote(models.Model):
    descricao = models.CharField(max_length=20,blank=False, null=False, validators=[MinLengthValidator(5)])
    valor_unitario = models.DecimalField(max_digits=8, decimal_places=2)

    class Meta:
        verbose_name = "Lote"

    def __str__(self) -> str:
        return self.descricao


class Categoria(models.Model):
    tipo = models.CharField(max_length=20,blank=False, null=False, validators=[MinLengthValidator(3)])
    sigla = models.CharField(max_length=2,blank=False, null=False)

    class Meta:
        verbose_name = "Categoria"

    def __str__(self) -> str:
        return self.tipo


class Congressista(models.Model):

    PASSEIO_OPCOES = (
        ('S', 'Sim'),
        ('N', 'Não'), )

    nome_completo = models.CharField(max_length=50, blank=False,null=False)
    cpf = models.CharField(max_length=11,blank=False,null=False)
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE, null=True,default=1)
    lote = models.ForeignKey(Lote,on_delete=models.DO_NOTHING,null=False)
    passeio_de_barco = models.CharField(max_length=1, choices=PASSEIO_OPCOES, default='N')
    ano = models.CharField(max_length=4,blank=False,null=False)
    cep = models.CharField("CEP", max_length=9, blank=True, null=True,
                           help_text="Digite um CEP válido para atualizar os campos abaixo.")  
    cidade = models.CharField(
        "Município", max_length=100, blank=True, null=True)
    uf = models.CharField("UF", max_length=2, blank=True,
                          null=True, validators=[validate_uf])
    proxima_parcela = models.DateField(blank=True, null=True)
    desconto = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

    # numero_parcelass = models.IntegerField(blank=True, null=True)
    total_parcelas = models.FloatField(default=0.0)

    class Meta:
        verbose_name = "Cadastro"
        verbose_name_plural = "Cadastro"
    
#Validação do Cpf:
    def clean(self):
        super().clean()
        if self.cpf:
            cpf = self.cpf.replace(".", "").replace("-", "").strip()
            if not CPF().validate(cpf):
                raise ValidationError('CPF inválido.')

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Congressista, self).save(*args, **kwargs)
    
# Calculo pra somar as parcelas:
    def valor_total_parcelas(self):
        return self.pagamento_set.aggregate(total=Sum('valor_parcela'))['total'] or 0
    
    def valor_total_categoria_8(self):
        categoria_id =[7,8,9]
        valor_total = self.pagamento_set.filter(categoria=categoria_id).aggregate(total=Sum('valor_parcela'))['total'] or 0        
        return valor_total
    
    def valor_total_baile(self):
        categoria_id =[2,3]
        valor_total = self.pagamento_set.filter(categoria=categoria_id).aggregate(total=Sum('valor_parcela'))['total'] or 0        
        return valor_total
    
    def valor_total_congresso(self):
        categoria_id =[1,]
        valor_total = self.pagamento_set.filter(categoria=categoria_id).aggregate(total=Sum('valor_parcela'))['total'] or 0        
        return valor_total

    def get_valor_restante(self):
        valor_total = self.lote.valor_unitario - self.desconto
        valor_parcelas = self.pagamento_set.aggregate(total=Sum('valor_parcela'))['total'] or 0
        return valor_total - valor_parcelas

    # def status_pagamento(self):
    #     if self.valor_restante <= 0:
    #         return 'Pago'
    #     else:
    #         return 'Pendente'

    def atualizar_proxima_parcela(self):
        if self.pagamento_set.exists():
            data_ultima_parcela = self.pagamento_set.latest('data_pagamento').data_pagamento
            proxima_parcela = data_ultima_parcela + timezone.timedelta(days=30)
        else:
            proxima_parcela = timezone.now() + timezone.timedelta(days=30)

        self.proxima_parcela = proxima_parcela
        self.save()
   
    @property
    def numero_parcelas(self):
        return self.pagamento_set.count()

    class Meta:
        verbose_name = "Congressista"

    def __str__(self) -> str:
        return self.nome_completo



class Pagamento(models.Model):

    TIPO =(
        ('CARTAO', 'Cartão de Credito'),
        ('ESPECIE', 'Espécie'),
        ('PIX', 'Pix'),
    )
    congressista = models.ForeignKey(Congressista, on_delete=models.CASCADE)
    valor_parcela = models.DecimalField(max_digits=10, decimal_places=2)
    numero_da_parcela = models.IntegerField(blank=True,null=True)
    tipo =models.CharField("Tipo de Pagamento", max_length=20, choices=TIPO)
    data_pagamento = models.DateField(auto_now_add=True)
    categoria= models.ForeignKey(Categoria,on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Pagamento"
        verbose_name_plural = "Pagamentos"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.congressista.atualizar_proxima_parcela()


    def __str__(self) -> str:
        return f"{self.congressista.nome_completo} - {self.data_pagamento}"

class Entrada(models.Model):
    
    descricao = models.CharField(max_length=100, blank=True, null=True)
    valor_unitario = models.DecimalField(verbose_name="Valor", max_digits=10, decimal_places=2)
    quantidade = models.IntegerField(default=1, blank=False, null=False)
    ano = models.IntegerField(default=date.today().year)    
    # nome_empresa = models.CharField(max_length=100)
    comprovante = models.ImageField(upload_to='comprovantes/', blank=True, null=False)
    valor_total_entrada = models.FloatField(blank=True, null=False, editable=False)

    def calcular_valor_total(self):
        
        if self.valor_unitario is not None and self.quantidade is not None:
            return self.valor_unitario * self.quantidade
        return 0

    def save(self, *args, **kwargs):        
        
        self.valor_total_entrada = self.calcular_valor_total()
        super().save(*args, **kwargs)

    def __str__(self):
        """
        Returns a string representation of the entry description.
        """
        return self.descricao

class Saida(models.Model):
    descricao = models.CharField(max_length=100,blank=True, null=False)
    valor_unitario = models.DecimalField(verbose_name="Valor",max_digits=10, decimal_places=2)
    quantidade = models.IntegerField(default=1, blank=False, null=False)
    ano = models.IntegerField(default=date.today().year)  
    # nome_empresa = models.CharField(max_length=100,blank=True, null=True)
    comprovante = models.ImageField(upload_to='comprovantes/',blank=True, null=False)
    valor_total_saida = models.FloatField(blank=True, null=False, editable=False)

    def calcular_valor_total(self):
        if self.valor_unitario is not None and self.quantidade is not None:
            return self.valor_unitario * self.quantidade
        return 0

    def save(self, *args, **kwargs):
        self.valor_total = self.calcular_valor_total()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.descricao

class Caixa (models.Model):    

    @property
    def congressitas(self):
        return Pagamento.objects.aggregate(total=Sum('valor_parcela'))['total'] or 0
    @property
    def day_user(self):
        categoria_id = [8,9]  
        return self.pagamento_set.filter(categoria=categoria_id).aggregate(total=Sum('valor_parcela'))['total'] or 0 @property
    @property
    def baile(self):
        categoria_id = [2,3]  
        return self.pagamento_set.filter(categoria=categoria_id).aggregate(total=Sum('valor_parcela'))['total'] or 0 
    @property
    def congressista(self):
        categoria_id = [1,]  
        return self.pagamento_set.filter(categoria=categoria_id).aggregate(total=Sum('valor_parcela'))['total'] or 0 
    
    @property
    def passeio(self):
        return Entrada.objects.filter(id__in=[4, 5, 6]).aggregate(Sum('valor_total_entrada'))['valor_total_entrada__sum']
        
    @property
    def entradas(self):
        return Entrada.objects.all().aggregate(Sum('valor_total_entrada'))['valor_total_entrada__sum']
    
    @property
    def saidas(self):
        return Saida.objects.all().aggregate(Sum('valor_total_saida'))['valor_total_saida__sum']

    @property
    def saldo(self):
        return Decimal(self.congressitas) + Decimal(self.entradas) - Decimal(self.saidas)

    
    def __str__(self):
        return self.congressitas

apps/user/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import TextInput

from .models import Congressista
class CongressistaFormAdmin(forms.ModelForm):
    model = Congressista
    fields = ("nome_completo", "cpf", "categoria", "lote", "ano", "cep",  "bairro", "cidade", "uf", "proxima_parcela")
    widgets = {
        "logradouro": TextInput(attrs={"readonly": "readonly", "style": "width: 270px; background: #f0f0f0;"}),
        "bairro": TextInput(attrs={"readonly": "readonly", "style": "width: 270px; background: #f0f0f0;"}),
        "cidade": TextInput(attrs={"readonly": "readonly", "style": "width: 270px; background: #f0f0f0;"}),
        "uf": TextInput(attrs={"readonly": "readonly", "style": "width: 270px; background: #f0f0f0;"})
    }

    def __init__(self, *args, **kwargs):
        super(CongressistaFormAdmin, self).__init__(*args, **kwargs)
        self.fields['cep'].widget.attrs['class'] = 'mask-cep'



    cep = forms.CharField(max_length=9, label='CEP', required=False, validators=[
        RegexValidator(
            regex='^\d{5}-\d{3}$',
            message='CEP com formato inválido.',
            code='invalid_cep'
        )
    ])


from django import forms

class LancamentoParcelaForm(forms.Form):
    nome_ou_cpf = forms.CharField(label="Nome ou CPF", max_length=50)
    valor_parcela = forms.DecimalField(label="Valor da Parcela")

apps/user/views.py
from django.db.models import Sum
from django.shortcuts import render
from .models import Congressista, Entrada, Saida

def caixa_view(request):
    total_parcelas = Congressista.objects.aggregate(total_parcelas=Sum('get_total_parcelas'))['total_parcelas'] or 0
    total_entrada = Entrada.objects.aggregate(total_entrada=Sum('get_valor_total'))['total_entrada'] or 0
    total_saida = Saida.objects.aggregate(total_saida=Sum('get_valor_total'))['total_saida'] or 0

    valor_total_caixa = total_parcelas + total_entrada - total_saida

    context = {
        'total_parcelas': total_parcelas,
        'total_entrada': total_entrada,
        'total_saida': total_saida,
        'valor_total_caixa': valor_total_caixa,
    }

    return render(request, 'caixa.html', context)

apps/user/templates/congressita/change_form_congressista.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify jazzmin %}
{% get_jazzmin_settings request as jazzmin_settings %}


{% block extrahead %}
<script src="{% static '/jquery.js' %}"></script>
<script>
    $(document).ready(function() {
    $("#id_cep").keyup(function() {
        if ($("#id_cep").val().length == 9) {
            var cep = $(this).val().replace(/[^0-9]/, '');
            if (cep) {
                var url = 'https://viacep.com.br/ws/'+cep+'/json/';
                $.ajax({
                        url: url,
                        dataType: 'jsonp',
                        crossDomain: true,
                        contentType: "application/json",
                        success : function(json){
                            if(json.logradouro){
                                $("#id_logradouro").val(json.logradouro);
                                $("#id_bairro").val(json.bairro);
                                $("#id_cidade").val(json.localidade);
                                $("#id_uf").val(json.uf);
                            }
                        }
                });
            }
        }
    });
});
</script>
    {{ block.super }}
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
    {{ media }}
{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}

{% if not is_popup %}
    {% block breadcrumbs %}
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a></li>
            <li class="breadcrumb-item">
                {% if has_view_permission %}
                    <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>
                {% else %}
                    {{ opts.verbose_name_plural|capfirst }}
                {% endif %}
            </li>
            <li class="breadcrumb-item active">
                {% if add %}
                    {% blocktrans with name=opts.verbose_name %}Add {{ name }}{% endblocktrans %}
                {% else %}
                    {{ original|truncatewords:"18" }}
                {% endif %}
            </li>
        </ol>
    {% endblock %}
{% endif %}

{% block content_title %} {{ opts.verbose_name_plural|capfirst }} {% endblock %}

{% block content %}

    <div id="content-main" class="col-12">
        <form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.model_name }}_form" novalidate>
            {% csrf_token %}
            {% block form_top %}{% endblock %}

            {% if errors %}
                <div class="alert alert-danger">
                    {% if errors|length == 1 %}
                        {% trans "Please correct the error below." %}
                    {% else %}
                        {% trans "Please correct the errors below." %}
                    {% endif %}
                </div>
                {% for error in adminform.form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <i class="icon fa fa-ban"></i>{{ error|capfirst }}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="row">
                {% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1">{% endif %}
                {% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}">{% endif %}

                {% block field_sets %}
                    <div class="col-15 col-lg-9">

                        <div class="card">
                            <div class="card-body">

                                {% get_changeform_template adminform as changeform_template %}
                                {% if change %}
                        <div class="d-flex justify-content-left">

                        </div>
                        {% endif %}

                                {% include changeform_template %}
                            </div>

                        </div>
                    </div>
                {% endblock %}

                {% block after_field_sets %}{% endblock %}

                {% block inline_field_sets %}{% endblock %}

                {% block after_related_objects %}{% endblock %}

                <div class="col-12 col-lg-3">
                    <div id="jazzy-actions" class="{{ jazzmin_ui.actions_classes }}">
                            {% block submit_buttons_bottom %}
                            {% submit_row %}
                            {% block object-tools %}
                                {% if change %}
                                    {% if not is_popup %}
                                        <div class="object-tools">
                                            {% block object-tools-items %}
                                                {% change_form_object_tools %}
                                                {% block extra_actions %}{% endblock %}
                                            {% endblock %}
                                        </div>
                                    {% endif %}
                                {% endif %}
                            {% endblock %}
                        {% endblock %}
                    </div>
                </div>

                {% block admin_change_form_document_ready %}
                    <script type="text/javascript" id="django-admin-form-add-constants" src="{% static 'admin/js/change_form.js' %}" {% if adminform and add %}data-model-name="{{ opts.model_name }}"{% endif %}></script>
                {% endblock %}

                {% prepopulated_fields_js %}
            </div>
        </form>
    </div>

{% endblock %}

apps/user/templates/congressita/change_list_caixa.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_list jazzmin %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">


{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'vendor/select2/css/select2.min.css' %}">

    {% if cl.formset or action_form %}
        <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
    {% endif %}
    {{ media.css }}
    {% if not actions_on_top and not actions_on_bottom %}
        <style>
            #changelist table thead th:first-child {width: inherit}
        </style>
    {% endif %}
{% endblock %}

{% block extrahead %}
    {{ block.super }}
    {{ media.js }}
{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-list{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a></li>
        <li class="breadcrumb-item active">{{ cl.opts.verbose_name_plural|capfirst }}</li>
    </ol>
{% endblock %}

{% block content_title %} {{ cl.opts.verbose_name_plural|capfirst }} {% endblock %}

{% block coltype %}flex{% endblock %}

    {% block page_actions %}
        <div class="col-12 col-md-auto d-flex align-items-center justify-content-end page-actions">
            {% block object-tools %}
                {% block object-tools-items %}
                    {% change_list_object_tools %}
                {% endblock %}
            {% endblock %}
        </div>
    {% endblock %}


{% block content %}

    {% block date_hierarchy %}{% if cl.date_hierarchy %}{% date_hierarchy cl %}{% endif %}{% endblock %}

    {% block search %}
        {% search_form cl %}
    {% endblock %}    

    <div class="col-12">
        <div>
            <form id="changelist-form" method="post"{% if cl.formset and cl.formset.is_multipart %}enctype="multipart/form-data"{% endif %} novalidate>{% csrf_token %}
                <div id="content-main">
                    {% if cl.formset and cl.formset.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% if cl.formset.total_error_count == 1 %}
                            {% trans "Please correct the error below." %}
                        {% else %}
                            {% trans "Please correct the errors below." %}
                        {% endif %}
                    </div>
                    {{ cl.formset.non_form_errors }}
                    {% endif %}
                    <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
                    <div class="row">
                        <div class="col-12">
                            {% if cl.formset %}
                                <div>{{ cl.formset.management_form }}</div>
                            {% endif %}

                            {% block result_list %}
                                <div class="change-list-actions row pb-3">
                                    <div class="col-12">
                                        {% if action_form and actions_on_top and cl.show_admin_actions %}
                                            {% admin_actions %}
                                        {% endif %}
                                    </div>
                                </div>
                                {% result_list cl %}
                                {% block after_results %}
                                <div class="row">
                                    <div class="col-md-12">
                                        <table class="table shadow-sm bg-white rounded table-bordered" id="total-table">
                                            <tbody>
                                                <tr class="total-row">
                                                    <td class="total-cell text-right" width="200px">
                                                        <strong>Valor Total dos Day User:</strong>
                                                    </td>
                                                    <td class="total-cell text-right" width="600px">
                                                        <strong>R$ {{ valor_total_categoria_8 }}</strong>
                                                    </td>
                                                </tr>
                                                <tr class="total-row">
                                                    <td class="total-cell text-right" width="200px">
                                                        <strong>Valor Total dos Bailes:</strong>
                                                    </td>
                                                    <td class="total-cell text-right" width="600px">
                                                        <strong>R$ {{ valor_total_baile }}</strong>
                                                    </td>
                                                </tr>
                                                <tr class="total-row">
                                                    <td class="total-cell text-right" width="200px">
                                                        <strong>Valor Total de Passeios:</strong>
                                                    </td>
                                                    <td class="total-cell text-right" width="400px">
                                                        <strong>R$ {{ passeio_de_barco }}</strong>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td></td>
                                                    <td></td>
                                                </tr>
                                                <tr class="total-row">
                                                    <td class="total-cell text-right" width="200px">
                                                        <strong>Valor Total de Congressita:</strong>
                                                    </td>
                                                    <td class="total-cell text-right" width="600px">
                                                        <strong>R$ {{ valor_total_congresso }}</strong>
                                                    </td>
                                                </tr>
                                                <tr>
                                                <tr class="total-row">
                                                    <td class="total-cell text-right" width="200px">
                                                        <strong>Valor Total de Entradas:</strong>
                                                    </td>
                                                    <td class="total-cell text-right" width="400px">
                                                        <strong>R$ {{ get_total_entradas }}</strong>
                                                    </td>
                                                </tr>                                                
                                                <tr class="total-row">
                                                    <td class="total-cell text-right" width="200px">
                                                        <strong>Valor Total de Saídas:</strong>
                                                    </td>
                                                    <td class="total-cell text-right" width="400px">
                                                        <strong class="text-danger" id="saldoAmount">R$ {{ get_total_saida }}</strong>
                                                    </td>
                                                </tr>
                                                    <td></td>
                                                    <td></td>
                                                </tr>
                                                <tr class="total-row">
                                                    <td class="total-cell text-right" width="200px">
                                                        <strong>Valor Total dos Pagamentos:</strong>
                                                    </td>
                                                    <td class="total-cell text-right" width="600px">
                                                        <strong id="saldoAmount">R$ {{ get_total_parcelas }}</strong>
                                                    </td>
                                                </tr>                                              
                                                
                                                <tr class="total-row">
                                                    <td class="total-cell text-right" width="200px">
                                                        <strong>Saldo Em Caixa Atualizado:</strong>
                                                    </td>
                                                    <td class="total-cell text-right" width="400px">
                                                        {% if saldo >= 0 %}
                                                            <strong id="saldoAmount" class="text-success">R$ {{ saldo|floatformat:2 }}</strong>
                                                        {% else %}
                                                            <strong id="saldoAmount" class="text-danger">R$ {{ saldo|floatformat:2 }}</strong>
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <script>
                                    // Obtém o elemento de saldo
                                    var saldoElement = document.getElementById("saldoAmount");
                                
                                    // Obtém o valor do saldo (removendo o símbolo R$)
                                    var saldoValue = parseFloat(saldoElement.innerText.replace("R$ ", ""));
                                
                                    // Formata o valor do saldo com até duas casas decimais e uma vírgula
                                    var formattedSaldo = saldoValue.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
                                
                                    // Define a cor com base no valor do saldo
                                    if (saldoValue > 0) {
                                        saldoElement.style.color = "darkgreen";  // Verde mais escuro
                                    } else {
                                        saldoElement.style.color = "red";  // Vermelho
                                    }
                                
                                    // Atualiza o texto do saldo formatado
                                    saldoElement.innerText = "R$ " + formattedSaldo;
                                </script>
                                
{% endblock %}
                                {% if action_form and actions_on_bottom and cl.show_admin_actions %}
                                    <div class="row">
                                        <div class="col-12">
                                            {% admin_actions %}
                                        </div>
                                    </div>
                                {% endif %}
                            {% endblock %}
                        </div>
                    </div>
                    <div class="row">
                        {% block pagination %}{% pagination cl %}{% endblock %}
                    </div>
                </div>
                </div>
            </form>
        </div>

        <br class="clear"/>
    </div>
{% endblock %}

{% block extrajs %}
    {{  block.super }}
    <script type="text/javascript" src="{% static 'vendor/select2/js/select2.min.js' %}"></script>
    <script>
        {% comment %} set filterInputLength default and custom values {% endcomment %}
        window.filterInputLengthDefault = 0;
        window.filterInputLength = {
            {% for k,v in cl.model_admin.filter_input_length.items %}
                '{{ k }}': {{ v }},
            {% endfor %}
        }
    </script>
    <script type="text/javascript" src="{% static 'jazzmin/js/change_list.js' %}"></script>
{% endblock %}

apps/user/templates/congressita/lancar_parcela.html
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Lançar Parcela</button>
</form>